import { useMemo, useRef, useState, useEffect } from "react";
import { trpc } from "@/lib/trpc";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Users, UserPlus, Accessibility, UsersRound, BriefcaseBusiness, Clock3, CalendarX2 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const nf = new Intl.NumberFormat("en-US");
const COLORS = ["#0b5d4d", "#c9ab72", "#8d2638", "#33423f", "#9c6b35", "#66736f", "#e3d7bd"];

function Stat({ title, value, hint, icon: Icon, tone }: { title: string; value: number | string; hint: string; icon: typeof Users; tone: string }) {
  return <Card className="relative min-w-0 overflow-hidden border-0 bg-white/95 shadow-sm"><div className={`absolute inset-y-0 right-0 w-1 ${tone}`} /><CardContent className="p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-xs text-slate-500">{title}</p><p className="mt-2 truncate text-2xl font-bold text-slate-900">{typeof value === "number" ? nf.format(value) : value}</p><p className="mt-1 truncate text-[11px] text-slate-400">{hint}</p></div><div className="rounded-2xl bg-[#0b5d4d]/10 p-2.5"><Icon className="h-5 w-5 text-[#0b5d4d]" /></div></div></CardContent></Card>;
}
function ChartBox({ children, className = "h-52" }: { children: React.ReactElement; className?: string }) { const ref = useRef<HTMLDivElement>(null); const [ready, setReady] = useState(false); useEffect(() => { const node = ref.current; if (!node) return; const update = () => setReady(node.clientWidth > 0 && node.clientHeight > 0); update(); const observer = new ResizeObserver(update); observer.observe(node); return () => observer.disconnect(); }, []); return <div ref={ref} className={className}>{ready ? <ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer> : null}</div>; }
function Distribution({ title, data, colors = COLORS }: { title: string; data: { name: string; value: number }[]; colors?: string[] }) { return <Card className="border-0 bg-white/95 shadow-sm"><CardHeader className="pb-1"><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent><ChartBox className="h-48"><BarChart data={data} layout="vertical" margin={{ top: 4, right: 8, left: 8, bottom: 0 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" /><XAxis type="number" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={102} tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value: number) => [nf.format(value), "الموظفون"]} /><Bar dataKey="value" radius={[0, 5, 5, 0]}>{data.map((_, i) => <Cell key={`${title}-${i}`} fill={colors[i % colors.length]} />)}</Bar></BarChart></ChartBox></CardContent></Card>; }

export default function HRAnalytics() {
  const { data, isLoading, error } = trpc.dashboard.overview.useQuery();
  const hrData = data?.hrMetrics as any;
  const administrationCounts = hrData?.monthlyAdministrationCounts ?? [];
  const adminNames = useMemo<string[]>(() => Array.from(new Set<string>(administrationCounts.flatMap((row: any) => row.administrations.map((item: any) => String(item.name)) as string[]))).slice(0, 6), [administrationCounts]);
  const adminSeries = useMemo(() => administrationCounts.map((row: any) => Object.fromEntries([['month', row.month], ...adminNames.map((name) => [name, row.administrations.find((item: any) => item.name === name)?.value || 0])])), [administrationCounts, adminNames]);
  if (isLoading) return <DashboardLayout><div className="p-8 text-center text-slate-500">جارٍ تحميل تحليلات الموارد البشرية...</div></DashboardLayout>;
  if (error || !data) return <DashboardLayout><div className="p-8 text-center text-red-600">تعذر تحميل تحليلات الموارد البشرية.</div></DashboardLayout>;
  const hr = data.hrMetrics as any;
  return <DashboardLayout><div dir="rtl" className="min-h-[calc(100vh-2rem)] bg-[#f5f1e8] p-3 text-slate-900 lg:p-4"><header className="mb-3 flex flex-col gap-1 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-[#0b5d4d]"><span className="h-2 w-2 rounded-full bg-[#c9ab72]" /> مركز بيانات الموارد البشرية</div><h1 className="text-2xl font-bold tracking-tight text-slate-950 lg:text-3xl">تحليلات الموارد البشرية</h1><p className="mt-1 text-sm text-slate-500">شرائح القوة العاملة الحالية، أنماط العمل، العمر، الخدمة والحركة الإدارية.</p></div><Badge variant="outline" className="w-fit rounded-full border-[#d8c398] bg-[#fbf6e9] px-3 py-1.5 text-[#0b5d4d]">لقطة البيانات: {hr.snapshotDate}</Badge></header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat title="الموظفون الجدد الحاليون" value={hr.currentNewEmployees} hint="أكواد تبدأ بـ GBC-" icon={UserPlus} tone="bg-[#0b5d4d]" /><Stat title="الموظفون القدامى" value={hr.legacyEmployees} hint="أكواد تبدأ بـ O-" icon={Users} tone="bg-[#c9ab72]" /><Stat title="ذوو الاحتياجات الخاصة" value={hr.specialNeeds} hint="مصنّفون صراحة في الحالة الصحية" icon={Accessibility} tone="bg-[#8d2638]" /><Stat title="معدل الغيابات" value={`${nf.format(hr.absenceRate)}%`} hint="غياب غير مبرر من إجمالي التحديثات" icon={CalendarX2} tone="bg-[#9c6b35]" /></section>
  <section className="mt-3 grid gap-3 lg:grid-cols-4"><Distribution title="الجنس" data={hr.genderDistribution} /><Distribution title="نوع الموظف" data={hr.employeeTypeDistribution} /><Distribution title="فئة العمر للموظفين الحاليين" data={hr.ageDistribution} /><Distribution title="نمط العمل في الضابطة الجمركية" data={hr.customsPoliceWorkPattern} /></section>
  <section className="mt-3 grid gap-3 lg:grid-cols-[0.9fr_1.1fr]"><Distribution title="سنوات الخدمة" data={hr.serviceDistribution} /><Card className="border-0 bg-white/95 shadow-sm"><CardHeader className="pb-1"><CardTitle className="flex items-center gap-2 text-sm"><BriefcaseBusiness className="h-4 w-4 text-[#0b5d4d]" /> أكثر المسميات الوظيفية انتشاراً</CardTitle></CardHeader><CardContent><ChartBox className="h-52"><BarChart data={hr.jobTitleDistribution} layout="vertical" margin={{ top: 4, right: 8, left: 8, bottom: 0 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" /><XAxis type="number" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value: number) => [nf.format(value), "الموظفون"]} /><Bar dataKey="value" fill="#0b5d4d" radius={[0, 5, 5, 0]} /></BarChart></ChartBox></CardContent></Card></section>
  <section className="mt-3 grid gap-3 lg:grid-cols-[1.2fr_0.8fr]"><Card className="border-0 bg-white/95 shadow-sm"><CardHeader className="pb-1"><CardTitle className="flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4 text-[#0b5d4d]" /> معدل الغيابات حسب الشهر</CardTitle><p className="text-[11px] text-slate-400">النسبة المئوية لسجلات الغياب غير المبرر</p></CardHeader><CardContent><ChartBox className="h-44"><LineChart data={hr.absenceByMonth} margin={{ top: 4, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="month" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 9 }} unit="%" axisLine={false} tickLine={false} /><Tooltip formatter={(value: number) => [`${nf.format(value)}%`, "معدل الغياب"]} /><Line type="monotone" dataKey="rate" stroke="#8d2638" strokeWidth={2} dot={{ r: 2 }} /></LineChart></ChartBox></CardContent></Card><Card className="border-0 bg-white/95 shadow-sm"><CardHeader className="pb-1"><CardTitle className="flex items-center gap-2 text-sm"><UsersRound className="h-4 w-4 text-[#0b5d4d]" /> ملخص الضابطة الجمركية</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold">{nf.format(hr.customsPoliceEmployeeCount)}</p><p className="mt-1 text-xs text-slate-400">موظفاً ضمن المديريات التي تحتوي على «الضابطة الجمركية»</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{hr.customsPoliceWorkPattern.map((item: any) => <div key={item.name} className="rounded-xl bg-[#f5f1e8] p-2"><p className="text-slate-500">{item.name}</p><p className="mt-1 font-bold">{nf.format(item.value)}</p></div>)}</div></CardContent></Card></section>
  <section className="mt-3"><Card className="border-0 bg-white/95 shadow-sm"><CardHeader className="pb-1"><CardTitle className="text-sm">عدد الموظفين في الإدارات حسب الأشهر</CardTitle><p className="text-[11px] text-slate-400">أعلى ست إدارات/جهات بحسب أكواد الموظفين الفريدة في كل شهر</p></CardHeader><CardContent><ChartBox className="h-56"><LineChart data={adminSeries} margin={{ top: 4, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="month" tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value: number, name: string) => [nf.format(value), name]} />{adminNames.map((name, index) => <Line key={name} type="monotone" dataKey={name} stroke={COLORS[index % COLORS.length]} strokeWidth={2} dot={false} />)}</LineChart></ChartBox></CardContent></Card></section>
  <p className="mt-2 text-center text-[11px] text-slate-400">تحليلات مجمّعة فقط — لا تعرض أسماء أو سجلات فردية. العمر والخدمة محسوبان حتى {hr.snapshotDate}.</p></div></DashboardLayout>;
}
